spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ep-alerts-ai-assistant
  ai:
    openai:
      api-key: ${openai_api_key}
      chat:
        options:
          model: gpt-4-0613